github:
  prebuilds:
    master: true
    branches: true
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    
image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 4040 # pyspark UI
    onOpen: notify
    
tasks:
  - name: setup
    init: |
      python -m venv .venv
      source .venv/bin/activate
      python -m pip install -r requirements.txt
      echo "source $(pwd)/.venv/bin/activate" >> ~/.bashrc
      echo "export PYTHONPATH=$(pwd)" >> ~/.bashrc
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      clear
    command: |  
      source .venv/bin/activate
      export PYTHONPATH=$(pwd)  

vscode:
  extensions:
    - ms-python.python